=== Badr-AKKA/Pogues-Model/src/main/resources/xsd/Questionnaire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://xml.insee.fr/schema/applis/pogues" targetNamespace="http://xml.insee.fr/schema/applis/pogues" elementFormDefault="qualified" attributeFormDefault="unqualified">

    <!-- TODO Internationalization -->

    <xs:element name="Survey">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:token"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="agency" type="xs:token"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Questionnaire">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="SequenceType">
                    <xs:sequence>
                        <xs:element ref="Survey"/>
                        <xs:element ref="ComponentGroup" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element ref="CodeLists" minOccurs="0"/>
                    </xs:sequence>
                    <xs:attribute name="agency" type="xs:token"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ComponentType" abstract="true">
        <xs:sequence>
            <xs:element name="Name" type="xs:token"/>
            <xs:element name="Label" type="xs:token" maxOccurs="unbounded"/>
            <xs:element name="Declaration" type="DeclarationType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Control" type="ControlType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="GoTo" type="GoToType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:element name="ComponentGroup">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:token"/>
                <xs:element name="Label" type="xs:token" maxOccurs="unbounded"/>
                <xs:element name="Declaration" type="DeclarationType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Member" type="ComponentType" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="QuestionType">
        <xs:complexContent>
            <xs:extension base="ComponentType">
                <xs:sequence>
                    <xs:element name="Response" type="ResponseType" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="open" type="xs:boolean"/>
                <xs:attribute name="simple" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ResponseType">
        <xs:sequence>
            <xs:element name="CodeListReference" type="xs:token" minOccurs="0"/>
            <xs:element name="Datatype" type="DatatypeType"/>
            <xs:element name="Value" type="xs:anyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="simple" type="xs:boolean"/>
        <xs:attribute name="mandatory" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="SequenceType">
        <xs:complexContent>
            <xs:extension base="ComponentType">
                <xs:sequence>
                    <xs:element name="Child" type="ComponentType" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="depth" type="xs:positiveInteger"/>
                <xs:attribute name="genericName" type="xs:token"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="DeclarationType">
        <xs:sequence>
            <xs:element name="Text" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="type" type="DeclarationTypeEnum"/>
        <xs:attribute name="disjoinable" type="xs:boolean"/> <!-- or isolable -->
    </xs:complexType>

    <xs:simpleType name="DeclarationTypeEnum">
        <xs:restriction base="xs:token">
            <xs:enumeration value="INSTRUCTION"/>
            <xs:enumeration value="COMMENT"/>
            <xs:enumeration value="HELP"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ControlType">
        <xs:sequence>
            <xs:element name="Description" type="xs:string"/>
            <xs:element name="Expression" type="ExpressionType"/>
            <xs:element name="FailMessage" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="criticity" type="ControlCriticityEnum"/>
    </xs:complexType>

    <xs:complexType name="GoToType">
        <xs:sequence>
            <xs:element name="Description" type="xs:string" minOccurs="0"/>
            <xs:element name="Expression" type="ExpressionType"/>
            <xs:element name="IfTrue" type="xs:token"/> <!-- Could be a REFID to a component -->
            <xs:choice minOccurs="0">
                <xs:element name="IfFalse" type="xs:token"/> <!-- Could be a REFID to a component -->
                <xs:element name="Next" type="xs:token"/> <!-- Could be a REFID to a go-to -->
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="ExpressionType">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="CodeLists">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CodeList" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="CodeListSpecification" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CodeList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:token"/>
                <xs:element name="Label" type="xs:token"/>
                <xs:element name="Code" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Value" type="xs:token"/>
                            <xs:element name="Label" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType> 
    </xs:element>

    <xs:element name="CodeListSpecification">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="uri" type="xs:anyURI"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType> 
    </xs:element>

    <!-- Data types -->

    <xs:complexType name="DatatypeType" abstract="true">
        <xs:attribute name="typeName" type="DatatypeTypeEnum" use="required"/>
        <xs:attribute name="visualizationHint" type="xs:token"/>
    </xs:complexType>
    
    <xs:complexType name="BooleanDatatypeType">
        <xs:complexContent>
            <xs:extension base="DatatypeType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="DateDatatypeType">
        <xs:complexContent>
            <xs:extension base="DatatypeType">
                <xs:sequence>
                    <xs:element name="Minimum" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Maximum" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Format" type="xs:token" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="NumericDatatypeType">
        <xs:complexContent>
            <xs:extension base="DatatypeType">
                <xs:sequence>
                    <xs:element name="Minimum" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Maximum" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Decimals" type="xs:nonNegativeInteger" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TextDatatypeType">
        <xs:complexContent>
            <xs:extension base="DatatypeType">
                <xs:sequence>
                    <xs:element name="MaxLength" type="xs:positiveInteger" minOccurs="0"/>
                    <xs:element name="Pattern" type="xs:token" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="DatatypeTypeEnum">
        <xs:restriction base="xs:token">
            <xs:enumeration value="BOOLEAN"/>
            <xs:enumeration value="DATE"/>
            <xs:enumeration value="NUMERIC"/>
            <xs:enumeration value="TEXT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ControlCriticityEnum">
        <xs:restriction base="xs:token">
            <xs:enumeration value="INFO"/>
            <xs:enumeration value="WARN"/>
            <xs:enumeration value="ERROR"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Badr-AKKA/Pogues-Model/src/main/resources/examples/fr.insee-POPO-QPO-DOC-codelists.xml
<?xml version="1.0" encoding="UTF-8"?>
<CodeLists xmlns="http://xml.insee.fr/schema/applis/pogues"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.insee.fr/schema/applis/pogues file:/src/main/resources/xsd/Questionnaire.xsd">
	<CodeList id="isg1g6zo">
		<Name />
		<Label>LISTE_TEST</Label>
		<Code>
			<Value />
			<Label>choix 1</Label>
		</Code>
		<Code>
			<Value />
			<Label>choix 2</Label>
		</Code>
		<Code>
			<Value />
			<Label>choix 3</Label>
		</Code>
		<Code>
			<Value />
			<Label>choix 4</Label>
		</Code>
		<Code>
			<Value />
			<Label>choix 5</Label>
		</Code>
	</CodeList>
	<CodeList id="isg1uorv">
		<Name />
		<Label>Oui_Non</Label>
		<Code>
			<Value />
			<Label>Oui</Label>
		</Code>
		<Code>
			<Value />
			<Label>Non</Label>
		</Code>
	</CodeList>
	<CodeList id="isg27fpv">
		<Name />
		<Label>LISTE_TEST_2</Label>
		<Code>
			<Value />
			<Label>choix 6</Label>
		</Code>
		<Code>
			<Value />
			<Label>choix 7</Label>
		</Code>
		<Code>
			<Value />
			<Label>choix 8</Label>
		</Code>
		<Code>
			<Value />
			<Label>choix 9</Label>
		</Code>
	</CodeList>
	<CodeList id="iw22dla9">
		<Name />
		<Label>DOMAINE</Label>
		<Code>
			<Value />
			<Label>Eaux usées</Label>
		</Code>
		<Code>
			<Value />
			<Label>Déchets hors radioactifs</Label>
		</Code>
		<Code>
			<Value />
			<Label>Protection de l’air</Label>
		</Code>
		<Code>
			<Value />
			<Label>Limitation des émissions de gaz à effet de serre</Label>
		</Code>
		<Code>
			<Value />
			<Label>Bruits et vibrations</Label>
		</Code>
		<Code>
			<Value />
			<Label>Sols, eaux souterraines et de surface</Label>
		</Code>
		<Code>
			<Value />
			<Label>Sites, paysages et biodiversité</Label>
		</Code>
		<Code>
			<Value />
			<Label>Autres (rayonnement, R&amp;D sur l’environnement…)</Label>
		</Code>
	</CodeList>
	<CodeList id="iw22fswu">
		<Name />
		<Label>L_SEXE</Label>
		<Code>
			<Value />
			<Label>Masculin</Label>
		</Code>
		<Code>
			<Value />
			<Label>Féminin</Label>
		</Code>
	</CodeList>

</CodeLists>
